# Generated by Django 5.1 on 2024-08-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=50)),
                ('bird_type', models.CharField(max_length=50)),
                ('live_weight', models.PositiveIntegerField()),
                ('curry_weight', models.FloatField()),
                ('day_rate', models.PositiveIntegerField()),
                ('total_sales_amount', models.FloatField()),
                ('expense', models.FloatField()),
                ('balance_cash', models.FloatField()),
                ('gpay', models.FloatField()),
            ],
        ),
    ]
