# Generated by Django 5.1 on 2024-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_weeklyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysheet',
            name='number_of_birds_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysheet',
            name='total_purchase_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysheet',
            name='total_stock_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysheet',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
