# Generated by Django 5.1 on 2024-09-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_dailysheet_number_of_birds_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='balance_cash',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='curry_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='expense',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='gpay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='live_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
